authResponse=$(curl --location -g --request POST "https://10.64.253.191/prweb/PRRestService/oauth2/v1/token" \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=${{ secrets.PEGA_DM_CLIENT_ID}}' \
--data-urlencode 'client_secret=${{ secrets.PEGA_DM_CLIENT_SECRET}}' \
--data-urlencode 'grant_type=client_credentials')

- name: Echo Client ID
  run: echo "${{ secrets.PEGA_DM_CLIENT_ID }}"
