name: Pega

on:
  workflow_dispatch:
    inputs:
      CallBackURL:
        description: "PDM CallBack URL"
        required: true
      OrchestratorURL:
        description: "URL on which the GitHub task is configured"
        required: true
      AuthResponse:
        description: "Pipeline name on which the GitHub task is configured"
        required: false
      TEST_SUITE_NAME:
        description: "Automation test suite (testing xml) to be executed"
        required: false
      BROWSER:
        description: Browser Name
        required: false

jobs:
  pega-github-custom-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print all the parameters
        run: |
          echo "CallBackURL: ${{ inputs.CallBackURL }}"
          echo "OrchestratorURL: ${{ inputs.OrchestratorURL }}"
          echo "PipelineName: ${{ inputs.PipelineName }}"
          echo "TEST_SUITE_NAME: ${{ inputs.TEST_SUITE_NAME }}"
          echo "BROWSER: ${{ inputs.BROWSER }}"

      - name: Update Pega DM Task
        run: |
          CallBackURL=$(echo "${{ inputs.CallBackURL }}" | sed 's/legacy_tasks/tasks/g')
          authToken=$(echo "${{ inputs.AuthResponse }}")
          echo "$authToken"
          updateTaskResponse=$(curl --location --request PUT "$CallBackURL" \
            --header "Authorization: Bearer $authToken" \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "taskStatus": "Resolved-Completed",
              "taskInfo": {
                "outputParameters": [
                  {
                    "name": "BuildNumber",
                    "type": "Text",
                    "value": "${{ github.run_number }}"
                  },
                  {
                    "name": "GitHubBuildURL",
                    "type": "Text",
                    "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            }')
          echo "updateTaskResponse: $updateTaskResponse"
